:sparkles: feat(action): Add an action to automatically build candy-board
Candy-Doc/candy-action pull request #1
Opened 2022-06-13 13:59 UTC by Tifloz

2022-06-14 12:19 UTC, M4gie approved these changes

2022-06-14 12:22 UTC, ctacquet approved these changes

2022-06-14 15:10 UTC, ecattez requested changes

2022-06-14 15:10 UTC, ecattez commented on Dockerfile
> +COPY ./ /usr/app
Copy only what you need to copy

2022-06-15 12:47 UTC, Tifloz commented
Deprecated since we don't need docker anymore

See #3 instead

2022-06-15 12:47 UTC, closed without merging